#!/bin/bash

set -e
set -u

cd $(dirname $0)

docker_target=${docker_target:-docker.i74.de:5000}
image_name=xilinx-ise
image_tag=14.7

## Checks that the tools listed in arguments are all installed.
check_tools() {
    for cmd in "$@"; do
        command -v $cmd >/dev/null || {
            >&2 echo "The following tools must be installed:"
            >&2 echo "    $@"
            >&2 echo "    Failed to find $cmd"
            >&2 echo
            exit 1
        }
    done
}

# Check environment
check_tools docker python3

# Start small webserver to hold install files
cd xilinx-installer
python3 -m http.server 8765 --bind 127.0.0.1 >/dev/null 2>&1 &
http_server_pid=$!
trap "echo 'stopping $http_server_pid' ; if [ $http_server_pid ] ; then kill $http_server_pid ; fi" SIGINT SIGTERM EXIT
cd ..

# Lint
docker run --rm -i hadolint/hadolint < Dockerfile || true

# Build
docker build --network host --rm -t ${docker_target}/${image_name}:${image_tag} .
docker tag ${docker_target}/${image_name}:${image_tag} ${docker_target}/${image_name}:latest

read -n1 -p "Do you want to push the image to the registry now [yN]? " answer
if [[ "${answer:-n}" == "y" ]]
then
    docker push ${docker_target}/${image_name}:${image_tag}
    docker push ${docker_target}/${image_name}:latest
fi
